In [238]:
import numpy as np

In [210]:
n, m = A.shape
R = np.zeros((m,m))
Q = np.zeros((n,m))

R[0,0] = np.linalg.norm(A[:,0])
Q[:,0] = A[:,0] / R[0,0]

for i in range(1,m):
    z = A[:,i]
    R[:i,i] = z @ Q[:, :i]
    z = z - Q[:,:i] @ R[:i,i]
    R[i,i] = np.linalg.norm(z)
    Q[:, i] = z / np.linalg.norm(z)

In [239]:
A = np.random.uniform(0,100,(4,6))

In [314]:
def qr_mgs(A, it=1):
    m, n = A.shape
    s = np.min([m,n])
    
    R = np.zeros((s,n))
    r = np.zeros((s,n))
    Q = np.zeros((m,s))

    for i in range(n):
        z = A[:,i]
        
        for k in range(it):
            for j in range(np.min([m,i])):
                r[j, i] = z @ Q[:,j]
                z = z - Q[:,j] * r[j,i]
                R[j, i] += r[j, i]
        
        if i < m:
            R[i,i] = np.linalg.norm(z)
            Q[:, i] = z / R[i,i]
        
    return Q, R

In [315]:
A = np.random.uniform(0,100,(10,4))
Q,R = qr_gs(A)

In [316]:
np.set_printoptions(precision=2, suppress=True)
R

array([[197.04, 151.31, 132.15, 107.58],
       [  0.  ,  68.22,  37.57,  34.48],
       [  0.  ,   0.  ,  81.24,  68.71],
       [  0.  ,   0.  ,   0.  ,  48.71]])

In [317]:
Q

array([[ 0.15,  0.01,  0.31,  0.49],
       [ 0.17, -0.05,  0.44, -0.47],
       [ 0.29, -0.01,  0.38,  0.3 ],
       [ 0.17,  0.39, -0.  ,  0.32],
       [ 0.45, -0.17, -0.38,  0.33],
       [ 0.2 ,  0.62,  0.33, -0.11],
       [ 0.5 , -0.55,  0.24, -0.21],
       [ 0.24, -0.05, -0.01,  0.2 ],
       [ 0.39,  0.15, -0.5 , -0.24],
       [ 0.37,  0.33, -0.13, -0.29]])

In [318]:
Q@R

array([[30.2 , 23.67, 45.39, 61.79],
       [33.16, 22.18, 56.21, 23.91],
       [56.31, 42.9 , 68.19, 71.18],
       [33.25, 51.88, 36.6 , 46.93],
       [87.71, 55.43, 21.26, 31.58],
       [40.  , 72.76, 76.56, 60.4 ],
       [98.85, 38.5 , 64.93, 40.91],
       [46.48, 32.28, 28.68, 32.71],
       [77.65, 69.91, 17.48,  2.05],
       [72.66, 78.65, 51.06, 28.33]])

In [319]:
A

array([[30.2 , 23.67, 45.39, 61.79],
       [33.16, 22.18, 56.21, 23.91],
       [56.31, 42.9 , 68.19, 71.18],
       [33.25, 51.88, 36.6 , 46.93],
       [87.71, 55.43, 21.26, 31.58],
       [40.  , 72.76, 76.56, 60.4 ],
       [98.85, 38.5 , 64.93, 40.91],
       [46.48, 32.28, 28.68, 32.71],
       [77.65, 69.91, 17.48,  2.05],
       [72.66, 78.65, 51.06, 28.33]])

In [262]:
Q@R

array([[45.9631, 49.8953, 86.4422, 50.2987, 66.1072, 48.2954],
       [32.7592, 54.4161, 82.8531, 95.9812,  2.6706, 34.7032],
       [50.884 , 78.5973, 27.0063, 61.5848, 97.3542, 50.3421],
       [50.0336, 85.8931, 82.0467, 96.9231, 91.397 , 62.493 ]])

In [198]:
A

array([[3.05375202, 8.21352504, 6.75210794, 1.77423015],
       [5.94669865, 0.02371081, 0.57892954, 5.49266631],
       [8.11838972, 1.8593878 , 7.54143515, 7.19854764],
       [9.62094251, 5.57731361, 5.16412125, 4.50403192]])

In [111]:
R[:i,i] = Q[:,i-1] @ z

R[:i,i]

array([4.68661932, 4.68661932])

In [112]:
qr = Q[:,i-1].reshape(-1,1) @ R[:i,i].reshape(1,-1)

qr

array([[ 4.1653158 ,  4.1653158 ],
       [-1.67025379, -1.67025379],
       [-1.16123683, -1.16123683],
       [ 0.69016393,  0.69016393]])

In [296]:
np.min([1,2])

1

In [100]:
R[:i,i].reshape(1,-1)

array([[4.68661932, 4.68661932]])

In [113]:
z = z - qr.reshape(-1,1)

z

ValueError: operands could not be broadcast together with shapes (4,1) (8,1) 

In [108]:
R[i,i] = np.linalg.norm(z)

R[i,i]

7.652081637246492

In [109]:
Q[:,i] = z[:,0] / R[i,i]

Q

array([[ 0.21424727,  0.88876768,  0.        ,  0.        ],
       [ 0.41721264, -0.35638777,  0.        ,  0.        ],
       [ 0.56957566, -0.24777707,  0.        ,  0.        ],
       [ 0.67499281,  0.14726264,  0.        ,  0.        ]])

In [89]:
R

array([[14.25340004,  6.59332636,  0.        ,  0.        ],
       [ 0.        ,  7.65208164,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [78]:
R[i,i]

7.652081637246492

In [45]:
Q

array([[0.21424727, 0.        , 0.        , 0.        ],
       [0.41721264, 0.        , 0.        , 0.        ],
       [0.56957566, 0.        , 0.        , 0.        ],
       [0.67499281, 0.        , 0.        , 0.        ]])

In [64]:
R

array([[14.25340004,  6.59332636,  0.        ,  0.        ],
       [ 0.        ,  7.65208164,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [177]:


def qr_gs(A):
    n,m = A.shape
    Q = np.zeros((n,m))    
    for i in range(m):
        vector = A[:, i]
        space = Q[:, :i]
        projection = vector @ space
        vector = vector - np.sum(projection * space, axis=1)        
        Q[:, i] = vector / np.linalg.norm(vector)
    return Q, Q.T @ A

In [178]:
Qa,Ra = qr_gs(A)

In [179]:
Qa

array([[ 0.21424727,  0.88876768,  0.13213234,  0.38305503],
       [ 0.41721264, -0.35638777, -0.40290591,  0.73252181],
       [ 0.56957566, -0.24777707,  0.78357835, -0.01396618],
       [ 0.67499281,  0.14726264, -0.45410663, -0.56257052]])

In [180]:
Ra

array([[14.25340004,  6.59332636,  9.46932   ,  9.81204044],
       [ 0.        ,  7.65208164,  4.68661932, -1.5010001 ],
       [ 0.        , -0.        ,  4.22316132,  1.61672078],
       [ 0.        ,  0.        , -0.        ,  2.06875385]])

In [181]:
np.set_printoptions(precision=8, suppress=True)
Ra

array([[14.25340004,  6.59332636,  9.46932   ,  9.81204044],
       [ 0.        ,  7.65208164,  4.68661932, -1.5010001 ],
       [ 0.        , -0.        ,  4.22316132,  1.61672078],
       [ 0.        ,  0.        , -0.        ,  2.06875385]])