In [1]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(precision=4, suppress=True)

In [39]:
def householder(A):
    m, n = A.shape
    Q = np.eye(m)
    H = A.copy()

    for k in range(n-2):
        v = H[k:, k] #vemu k-tý sloupec, od k+1 prvku
        
        norm_v = np.sign(v[0])*np.linalg.norm(v)
        v[0] = v[0] + norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,1)
        
        print(f'v: {v}')
        H[k:, k:] = H[k:, k:] - 2 * v @ (v.T @ H[k:, k:])
        print(f'H: {H}')
        H[k, k] = -norm_v
        H[k+1:, k] = 0
        print(f'H: {H}')
        #H[:, k:] = H[:, k:] - 2 * (H[:, k:] @ v) @ v.T
        #print(f'H: {H}')                                             
        Q[k:] = Q[k:] - 2 * v @ (v.T @ Q[k:])
        
    return Q, H

In [40]:
A = np.random.rand(4,4)

In [41]:
Q,R = householder(A)

v: [[0.8518]
 [0.3087]
 [0.3939]
 [0.155 ]]
H: [[-1.523  -0.4554 -1.1025 -0.7493]
 [-0.552   0.1703  0.2035 -0.5041]
 [-0.7044 -0.1698  0.2786 -0.3066]
 [-0.2771  0.8088  0.6177  0.5647]]
H: [[-1.0496 -0.4554 -1.1025 -0.7493]
 [ 0.      0.1703  0.2035 -0.5041]
 [ 0.     -0.1698  0.2786 -0.3066]
 [ 0.      0.8088  0.6177  0.5647]]
v: [[ 0.7752]
 [-0.1298]
 [ 0.6183]]
H: [[-1.0496 -0.4554 -1.1025 -0.7493]
 [ 0.     -1.014  -0.5771 -0.5012]
 [ 0.      0.1698  0.4093 -0.3071]
 [ 0.     -0.8088 -0.0049  0.567 ]]
H: [[-1.0496 -0.4554 -1.1025 -0.7493]
 [ 0.     -0.8437 -0.5771 -0.5012]
 [ 0.      0.      0.4093 -0.3071]
 [ 0.      0.     -0.0049  0.567 ]]


In [42]:
np.allclose(Q@A@Q.T, R)

False

In [43]:
np.allclose(Q@R,A)

False

In [44]:
R

array([[-1.0496, -0.4554, -1.1025, -0.7493],
       [ 0.    , -0.8437, -0.5771, -0.5012],
       [ 0.    ,  0.    ,  0.4093, -0.3071],
       [ 0.    ,  0.    , -0.0049,  0.567 ]])

In [45]:
Q@A@Q.T

array([[ 1.6505,  0.1711,  0.2053, -0.5389],
       [ 0.9634,  0.3857, -0.279 ,  0.3762],
       [-0.1936,  0.4067,  0.2399,  0.038 ],
       [-0.1464, -0.5218,  0.0059,  0.1665]])

In [46]:
np.allclose(la.qr(A)[1],R)

False

In [47]:
Q@Q.T

array([[ 1., -0., -0., -0.],
       [-0.,  1.,  0., -0.],
       [-0.,  0.,  1.,  0.],
       [-0., -0.,  0.,  1.]])

In [16]:
a = np.array([1,2,3])
b = np.random.rand(3,4)
aa = a @ b
print(aa)
c = np.array([2,3,4])
print(np.outer(c,aa))

[3.23236234 2.32564168 2.42584022 1.42135039]
[[ 6.46472468  4.65128336  4.85168044  2.84270077]
 [ 9.69708701  6.97692505  7.27752066  4.26405116]
 [12.92944935  9.30256673  9.70336088  5.68540154]]


In [14]:
a

array([1, 2, 3])

In [19]:
b

array([[0.97380544, 0.10091618, 0.62358255, 0.23136363],
       [0.64351942, 0.22342711, 0.37959746, 0.08393342],
       [0.32383935, 0.59262376, 0.34768758, 0.34070664]])

In [18]:
b[1:]


array([[0.64351942, 0.22342711, 0.37959746, 0.08393342],
       [0.32383935, 0.59262376, 0.34768758, 0.34070664]])

In [41]:
A = np.random.rand(3,3)
A

array([[0.4274, 0.567 , 0.8856],
       [0.5377, 0.6529, 0.8275],
       [0.3602, 0.4611, 0.2433]])

In [47]:
m, n = A.shape
R = np.copy(A)
Q = np.eye(m)
#for k in range(n):
k = 0
v = R[k:,k]
print(f'v: {v}')
v_norm = np.sign(v[0]) * la.norm(v)
v[0] = v[0] + v_norm
v = v / la.norm(v)
print(f'v_norm: {v}')
print(R[k:,k:])
print(f'2vv.T: {2*np.outer(v,(v @ R[k:,k:]))}')
R[k:,k:] = R[k:,k:] - 2*np.outer(v,(v @ R[k:,k:]))
R[k,k] = -v_norm
R[k+1:,k] = 0
Q[k:] = Q[k:] - 2*np.outer(v,(v @ Q[k:]))
#return Q.T, R
print(R)

v: [0.4274 0.5377 0.3602]
v_norm: [0.8807 0.3936 0.2637]
[[1.2031 0.567  0.8856]
 [0.5377 0.6529 0.8275]
 [0.3602 0.4611 0.2433]]
2vv.T: [[2.4061 1.5462 2.0604]
 [1.0754 0.6911 0.9209]
 [0.7203 0.4629 0.6168]]
[[-0.7756 -0.9793 -1.1748]
 [ 0.     -0.0382 -0.0934]
 [ 0.     -0.0018 -0.3735]]


In [98]:
def qr_householder(A):
    
    n, m = A.shape
    o = np.min([n,m])
    if n > m: 
        o += 1
    R = np.copy(A)
    Q = np.identity(n)
    I = np.identity(n) # matice s vektory báze

    for i in range(o-2):
        x = R[i+1:,i].reshape(n-i-1,1) 
        e = I[i+1:,i].reshape(n-i-1,1) 

        q = x + (np.sign(x.item(0)) * np.linalg.norm(x)) * e
        q = q / np.linalg.norm(q)

        H_q = np.identity(n-i-1) - 2 * q @ q.T
        H_q = np.pad(H_q,(i,0),'constant')

        Q_i = np.array([[float(k == l) if k < i else 0 for k in range(1,n)] for l in range(1,n)]) + H_q

        Q = Q_i @ Q
        R = Q_i @ R
    
    return Q.T, R

In [99]:
A


array([[0.0406, 0.5517, 0.6923, 0.1954, 0.9147],
       [0.4921, 0.2601, 0.1066, 0.7416, 0.268 ],
       [0.1247, 0.6053, 0.0502, 0.7599, 0.4438],
       [0.0665, 0.0245, 0.1453, 0.6035, 0.485 ],
       [0.1468, 0.0246, 0.6011, 0.6597, 0.5569]])

In [100]:
Q, R = qr_householder(A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [89]:
Q@A@Q.T

array([[ 0.5293, -0.214 , -0.073 , -0.9612, -0.3386],
       [-0.6782,  0.3844, -0.2546,  0.8322, -0.7182],
       [-0.0448, -0.1821, -0.3343,  0.1088, -0.1988],
       [-0.4187,  0.1225,  0.3974,  1.0214, -0.5277],
       [ 0.4028, -0.0004, -0.072 , -0.4709, -0.0894]])

In [90]:
Q@R

array([[0.0406, 0.5517, 0.6923, 0.1954, 0.9147],
       [0.4921, 0.2601, 0.1066, 0.7416, 0.268 ],
       [0.1247, 0.6053, 0.0502, 0.7599, 0.4438],
       [0.0665, 0.0245, 0.1453, 0.6035, 0.485 ],
       [0.1468, 0.0246, 0.6011, 0.6597, 0.5569]])

In [38]:
A

array([[0.6831, 0.2257, 0.3629, 0.2795],
       [0.5136, 0.0667, 0.0848, 0.4567],
       [0.1598, 0.4041, 0.5397, 0.695 ],
       [0.7455, 0.9121, 0.5144, 0.9953]])

In [57]:
def hessenberg(A):
    m, n = A.shape
    Q = np.eye(m)
    H = A.copy()

    for k in range(n-2):
        v = H[k+1:, k] #vemu k-tý sloupec, od k+1 prvku
        
        norm_v = np.sign(v[0])*np.linalg.norm(v)
        v[0] = v[0] + norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,1)
        
        H[k+1:, k:] = H[k+1:, k:] - 2 * v @ (v.T @ H[k+1:, k:])
        H[k+1, k] = -norm_v
        H[k+2:, k] = 0
        H[:, k+1:] = H[:, k+1:] - 2 * (H[:, k+1:] @ v) @ v.T
                                             
        Q[k+1:] = Q[k+1:] - 2 * v @ (v.T @ Q[k+1:])
        
        
        v = H[k, k+1:] #vemu k-tý řádek
        
        norm_v = np.sign(v[0])*np.linalg.norm(v)
        v[0] = v[0] + norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,-1)
        
        H[k+1:, k:] = H[k+1:, k:] - 2 * v @ (v.T @ H[k+1:, k:])
        H[k+1, k] = -norm_v
        H[k+2:, k] = 0
        H[:, k+1:] = H[:, k+1:] - 2 * (H[:, k+1:] @ v) @ v.T
                                             
        Q[k+1:] = Q[k+1:] - 2 * v @ (v.T @ Q[k+1:])
        
        
        
        
        
        
        
        
    return Q, H

[[-7. -7. -7. -7.]
 [-7. -7. -7. -7.]
 [-7. -7. -7. -7.]
 [-7. -7. -7. -7.]]
[[ 1.  0.  0.  0.]
 [ 0. -5. -5. -5.]
 [ 0. -5. -5. -5.]
 [ 0. -5. -5. -5.]]


In [64]:
v = np.array([1,2,3])

In [67]:
v.reshape(1,-1)

array([[1, 2, 3]])