In [1]:
import numpy as np
from rogues import lauchli # Python and Numpy port of Prof. Nicholas Higham's matlab test matrices
import pandas as pd
import time

np.set_printoptions(precision=4, suppress=True)

In [86]:
def qr_householder(A):
    
    #n = np.min(A.shape)
    n, m = A.shape
    o = np.min([n,m])
    if n > m: 
        o += 1
    R = np.copy(A)
    Q = np.identity(n)
    I = np.identity(n) # matice s vektory báze

    for i in range(o-1):
        print(i)
        x = R[i:,i].reshape(n-i,1) 
        e = I[i:,i].reshape(n-i,1) 

        q = x + (np.sign(x.item(0)) * np.linalg.norm(x)) * e
        q = q / np.linalg.norm(q)

        H_q = np.identity(n-i) - 2 * q @ q.T
        H_q = np.pad(H_q,(i,0),'constant')

        Q_i = np.array([[float(k == l) if k < i else 0 for k in range(n)] for l in range(n)]) + H_q

        Q = Q_i @ Q
        R = Q_i @ R
    
    return Q.T, R

In [103]:
A = np.random.uniform(0,100,(6,4))
Q, R = qr_householder(A)

print(f'Q:\n{Q}')
print(f'R:\n{R}')

0
1
2
3
Q:
[[-0.1167  0.6127 -0.1503  0.3797 -0.4438 -0.4973]
 [-0.4173 -0.0113 -0.6752  0.3948  0.3994  0.2331]
 [-0.0443  0.6744 -0.1748 -0.652   0.1889  0.2277]
 [-0.7324 -0.2779 -0.0484 -0.3656 -0.5002  0.0115]
 [-0.4996  0.1278  0.5519  0.0596  0.5556 -0.3424]
 [-0.1558  0.2759  0.4289  0.371  -0.2211  0.7274]]
R:
[[ -98.6578 -122.6773 -112.6894 -119.6759]
 [   0.      128.8261   73.6313   73.6784]
 [  -0.       -0.      -74.2668   18.1857]
 [   0.       -0.       -0.       61.909 ]
 [  -0.        0.        0.       -0.    ]
 [  -0.        0.        0.       -0.    ]]


In [101]:
np.allclose(A, Q @ R)

True

In [32]:
n, m = A.shape
o = np.min([n,m])

In [33]:
r = np.copy(A[:o,:m])

In [34]:
A

array([[ 2.4716, 92.1948, 38.0735, 57.6491],
       [31.619 , 39.866 , 53.7656, 29.653 ],
       [ 6.6476, 41.7207, 12.1078, 82.6036],
       [ 8.9796, 33.9384, 54.9844,  1.1252],
       [76.4645, 54.5281, 19.9026, 90.2216],
       [51.4644, 74.0196, 22.755 , 26.3884]])

In [35]:
r

array([[ 2.4716, 92.1948, 38.0735, 57.6491],
       [31.619 , 39.866 , 53.7656, 29.653 ],
       [ 6.6476, 41.7207, 12.1078, 82.6036],
       [ 8.9796, 33.9384, 54.9844,  1.1252]])