In [ ]:
import numpy as np
import scipy as sp

#householderova reflexe
#vstup: vektor a
#výstup: vektor u a v (nevim co je ???)
def housegen(a):
    u = a
    v = np.linalg.norm(a)
    if v == 0:
        u[0] = np.sqrt(2)
        return u, v
    if u[0] != 0:
        ro = u[0]

In [28]:
import numpy as np

def hessenberg_reduce(A):
    n, m = A.shape
    H = A.copy() # Transformed matrix so far
    Q = np.eye(n) # Orthogonal transform so far
    

    for j in range(n-2):
        # Find H = I - beta*u*u' to put zeros below R[j,j]
        x = H[j+1:, j] #vemu j-tý sloupec
        normx = np.linalg.norm(x) # vypočtu z něj normu
        ro = -np.sign(x[0]) # ro = -1/1 podle toho, zda je x[0] kladné nebo záporné
        u1 = x[0] - ro * normx # u1 = první prvek j-tého sloupce od kterého odečtu normu(oznaménkovanou)
        u = x / u1 # do u uložim první sloupec, který vydělím u1
        u[0] = 1 # první prvek u ještě nasatvím na 1
        beta = -ro * u1 / normx # beta nevim co 

        H[j+1:, :] = H[j+1:, :] - beta * np.outer(u, u).dot(H[j+1:, :])
        Q[:, j+1:] = Q[:, j+1:] - beta * Q[:, j+1:].dot(np.outer(u, u))
        
    return Q, H

In [29]:
A = np.random.rand(5,5)

In [30]:
Q,H = hessenberg_reduce(A)

In [80]:
print(A)

[[0.67944829 0.48780161 0.36605012 0.69521616 0.44494077]
 [0.37258175 0.68181531 0.06199577 0.54949625 0.75466711]
 [0.69451745 0.37326143 0.95182627 0.41641494 0.78526393]
 [0.90392383 0.38058289 0.88794242 0.76931024 0.93739307]
 [0.3841206  0.93341526 0.71691721 0.34490743 0.03873032]]


In [32]:
print(np.around(Q,decimals=5))

[[ 1.       0.       0.       0.       0.     ]
 [ 0.      -0.29587  0.47757 -0.76595 -0.31259]
 [ 0.      -0.55152 -0.19194  0.38502 -0.71466]
 [ 0.      -0.71781 -0.37666 -0.18439  0.55577]
 [ 0.      -0.30503  0.7702   0.48071  0.28752]]


In [33]:
print(np.around(H,decimals=5))

[[ 0.67945  0.4878   0.36605  0.69522  0.44494]
 [-1.25928 -0.96549 -1.39934 -1.04966 -1.34105]
 [-0.       0.82953  0.06463  0.15837 -0.11357]
 [ 0.      -0.       0.49989 -0.23661 -0.42992]
 [-0.       0.       0.       0.05736 -0.26499]]


In [79]:
from scipy import linalg

HS = linalg.hessenberg(A)
print(np.around(HS,decimals=5))

[[ 0.67945 -0.98096  0.24077  0.03379 -0.17846]
 [-1.25928  2.21994 -0.84194  0.11451 -0.37477]
 [ 0.      -0.36317  0.34935  0.63028 -0.23899]
 [ 0.       0.       0.30185 -0.47107 -0.39179]
 [ 0.       0.       0.       0.0414   0.34346]]


In [78]:
A

array([[0.67944829, 0.48780161, 0.36605012, 0.69521616, 0.44494077],
       [0.37258175, 0.68181531, 0.06199577, 0.54949625, 0.75466711],
       [0.69451745, 0.37326143, 0.95182627, 0.41641494, 0.78526393],
       [0.90392383, 0.38058289, 0.88794242, 0.76931024, 0.93739307],
       [0.3841206 , 0.93341526, 0.71691721, 0.34490743, 0.03873032]])

In [40]:
np.matmul(np.matmul(np.transpose(Q),A),Q)

array([[ 6.79448285e-01, -9.80959510e-01,  2.43528873e-01,
        -1.46999798e-01,  1.00220199e-01],
       [-1.25928494e+00,  2.21993721e+00, -8.30002311e-01,
        -2.50363255e-01,  3.32925259e-01],
       [ 5.59689034e-17, -3.60110642e-01,  2.36624515e-01,
        -6.94297099e-01, -2.50130049e-01],
       [ 3.53990222e-17,  2.52845447e-02, -3.37954389e-01,
         2.94319110e-02, -6.12360957e-01],
       [ 1.00684210e-16,  3.96586095e-02, -2.25704391e-01,
        -1.37960645e-01, -4.43114944e-02]])

In [37]:
Q

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.2958677 ,  0.4775657 , -0.76594974, -0.31259287],
       [ 0.        , -0.55151731, -0.19194446,  0.3850234 , -0.71466283],
       [ 0.        , -0.71780723, -0.37666284, -0.1843911 ,  0.55576777],
       [ 0.        , -0.30503073,  0.7702035 ,  0.48070563,  0.28751508]])

In [39]:

print(np.around(np.matmul(Q,np.transpose(Q)),decimals=5))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1.  0. -0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -0.  0.  1.]]


In [46]:
e,_ = np.linalg.eig(HS)
e

array([ 2.91331374, -0.67686773,  0.07992681,  0.45779468,  0.34696293])

In [44]:
e,_ = np.linalg.eig(A)
e

array([ 2.91331374, -0.67686773,  0.07992681,  0.45779468,  0.34696293])

In [45]:
e,_ = np.linalg.eig(H)
e

array([-0.0822787 +1.00638507j, -0.0822787 -1.00638507j,
        0.12610727+0.j        , -0.34228698+0.27846719j,
       -0.34228698-0.27846719j])

In [174]:
#https://byumcl.bitbucket.io/bootcamp2014/_downloads/Lab13v1.pdf

import numpy as np

def hessenberg_reduce2(A):
    m, n = A.shape
    H = A.copy() # Transformed matrix so far
    Q = np.eye(n) # Orthogonal transform so far
    

    for j in range(n-2):
        # Find H = I - beta*u*u' to put zeros below R[j,j]
        vk = H[j+1:, j] #vemu j-tý sloupec, od j+1 prvku
        
        norm_vk = -np.linalg.norm(vk) # vypočtu z něj normu
        vk[0] =vk[0] - np.sign(vk[0])*norm_vk
        vk = vk/np.linalg.norm(vk)
        
        #        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * vk.reshape(-1,1).dot(vk.reshape(1,-1).dot(H[j+1:, j+1:]))
        
        v = vk.reshape(-1,1)
        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * v @ (v.T @ H[j+1:, j+1:])
        H[j+1, j] = norm_vk
        H[j+2:, j] = 0
        H[:, j+1:] = H[:, j+1:] - 2 * (H[:, j+1:] @ v) @ v.T
                                             
        Q[j+1:] = Q[j+1:] - 2 * v @ (v.T @ Q[j+1:])
    return Q, H

In [ ]:
# podle fce v matlabu
#[[0.67944829 0.48780161 0.36605012 0.69521616 0.44494077]
# [0.37258175 0.68181531 0.06199577 0.54949625 0.75466711]
# [0.69451745 0.37326143 0.95182627 0.41641494 0.78526393]
# [0.90392383 0.38058289 0.88794242 0.76931024 0.93739307]
# [0.3841206  0.93341526 0.71691721 0.34490743 0.03873032]]

# https://math.stackexchange.com/questions/732924/reducing-a-matrix-to-upper-hessenberg-form-using-householder-transformations-in


#### JEŠTĚ ZAZNAMENÁVAT MATICI Q - ale jak???

import numpy as np

def hessenberg_reduce3(A):
    m, n = A.shape
    H = A.copy() # Transformed matrix so far
    #Q = np.eye(n) # Orthogonal transform so far
    

    for j in range(n-2):
        vk = H[j+1:, j] #vemu j-tý sloupec
        norm_vk = -np.linalg.norm(vk) # vypočtu z něj normu
        if vk[0] < 0:
            norm_vk = -norm_vk
        vk[0] = vk[0] - norm_vk
        #vk[0] =vk[0] + np.sign(vk[0])*norm_vk
        vk = vk/np.linalg.norm(vk)
                
        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * vk.reshape(-1,1).dot(vk.reshape(1,-1).dot(H[j+1:, j+1:]))
        H[j+1, j] = norm_vk
        H[j+2:, j] = 0
        H[:, j+1:] = H[:, j+1:] - 2 * (H[:, j+1:].dot(vk.reshape(-1,1)).dot(vk.reshape(1,-1))) 
        
    return H #Q, H

In [164]:
A

array([[0.63543148, 0.11091331, 0.65776136, 0.25947158],
       [0.58228463, 0.15277821, 0.01688175, 0.13602832],
       [0.95371401, 0.81910767, 0.77008896, 0.90681151],
       [0.03695714, 0.75844217, 0.24511761, 0.14947362]])

In [165]:
Q2,H2 = hessenberg_reduce2(A)

In [59]:
e

array([ 2.91331374, -0.67686773,  0.07992681,  0.45779468,  0.34696293])

In [48]:
np.dot(e,e)

9.281894407764215

In [51]:
np.linalg.norm(e)**2

9.281894407764215

In [52]:
H


array([[ 6.79448285e-01,  4.87801612e-01,  3.66050119e-01,
         6.95216159e-01,  4.44940772e-01],
       [-1.25928494e+00, -9.65492753e-01, -1.39934447e+00,
        -1.04966206e+00, -1.34104974e+00],
       [-7.36073902e-18,  8.29534412e-01,  6.46265058e-02,
         1.58370348e-01, -1.13574843e-01],
       [ 1.15630779e-16, -1.20247905e-16,  4.99887198e-01,
        -2.36612036e-01, -4.29921143e-01],
       [-4.45284405e-17,  1.00957142e-16,  0.00000000e+00,
         5.73590349e-02, -2.64994088e-01]])

In [53]:
HS

array([[ 0.67944829, -0.98095951,  0.2407682 ,  0.03379268, -0.17846027],
       [-1.25928494,  2.21993721, -0.84193756,  0.11450613, -0.37477236],
       [ 0.        , -0.36316909,  0.34935187,  0.63027784, -0.23898701],
       [ 0.        ,  0.        ,  0.30185458, -0.47106608, -0.39179038],
       [ 0.        ,  0.        ,  0.        ,  0.04140215,  0.34345914]])

In [54]:
np.matmul(np.transpose(e),HS)

array([ 2.83181537, -4.38947363,  1.43742367, -0.12996725, -0.34553288])

In [62]:
aa= np.array([1,2,3])

In [65]:
np.transpose(aa)

array([1, 2, 3])

In [68]:
bb = np.eye(3)

In [69]:
bb

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.matmul(aa.T,bb)

array([1., 2., 3.])

In [72]:
aa.dot(bb)

array([1., 2., 3.])

In [74]:
bb.dot(aa.T)

array([1., 2., 3.])

In [77]:
np.inner(bb,bb)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
# podle fce v matlabu
#[[0.67944829 0.48780161 0.36605012 0.69521616 0.44494077]
# [0.37258175 0.68181531 0.06199577 0.54949625 0.75466711]
# [0.69451745 0.37326143 0.95182627 0.41641494 0.78526393]
# [0.90392383 0.38058289 0.88794242 0.76931024 0.93739307]
# [0.3841206  0.93341526 0.71691721 0.34490743 0.03873032]]

# https://math.stackexchange.com/questions/732924/reducing-a-matrix-to-upper-hessenberg-form-using-householder-transformations-in


#### JEŠTĚ ZAZNAMENÁVAT MATICI Q - ale jak???

import numpy as np

def hessenberg_reduce3(A):
    m, n = A.shape
    H = A.copy() # Transformed matrix so far
    #Q = np.eye(n) # Orthogonal transform so far
    

    for j in range(n-2):
        vk = H[j+1:, j] #vemu j-tý sloupec
        norm_vk = -np.linalg.norm(vk) # vypočtu z něj normu
        if vk[0] < 0:
            norm_vk = -norm_vk
        vk[0] = vk[0] - norm_vk
        #vk[0] =vk[0] + np.sign(vk[0])*norm_vk
        vk = vk/np.linalg.norm(vk)
                
        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * vk.reshape(-1,1).dot(vk.reshape(1,-1).dot(H[j+1:, j+1:]))
        H[j+1, j] = norm_vk
        H[j+2:, j] = 0
        H[:, j+1:] = H[:, j+1:] - 2 * (H[:, j+1:].dot(vk.reshape(-1,1)).dot(vk.reshape(1,-1))) 
        
    return H #Q, H

In [84]:
A

array([[0.67944829, 0.48780161, 0.36605012, 0.69521616, 0.44494077],
       [0.37258175, 0.68181531, 0.06199577, 0.54949625, 0.75466711],
       [0.69451745, 0.37326143, 0.95182627, 0.41641494, 0.78526393],
       [0.90392383, 0.38058289, 0.88794242, 0.76931024, 0.93739307],
       [0.3841206 , 0.93341526, 0.71691721, 0.34490743, 0.03873032]])

In [120]:
hessenberg_reduce3(A)

array([[ 0.67944829, -0.98095951,  0.2407682 ,  0.03379268, -0.17846027],
       [-1.25928494,  2.21993721, -0.84193756,  0.11450613, -0.37477236],
       [ 0.        , -0.36316909,  0.34935187,  0.63027784, -0.23898701],
       [ 0.        ,  0.        ,  0.30185458, -0.47106608, -0.39179038],
       [ 0.        ,  0.        ,  0.        ,  0.04140215,  0.34345914]])

In [94]:
A

array([[0.67944829, 0.48780161, 0.36605012, 0.69521616, 0.44494077],
       [0.37258175, 0.68181531, 0.06199577, 0.54949625, 0.75466711],
       [0.69451745, 0.37326143, 0.95182627, 0.41641494, 0.78526393],
       [0.90392383, 0.38058289, 0.88794242, 0.76931024, 0.93739307],
       [0.3841206 , 0.93341526, 0.71691721, 0.34490743, 0.03873032]])

In [95]:
A[1:,0]

array([0.37258175, 0.69451745, 0.90392383, 0.3841206 ])

In [96]:
aa

array([1, 2, 3])

In [97]:
bb

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
aa*bb

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [99]:
aa.dot(bb)

array([1., 2., 3.])

In [104]:
np.inner(aa.T,(aa.dot(bb)))

14.0

In [114]:
aa.reshape((-1, 1)).dot(aa.reshape(1,-1).dot(bb))

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [110]:
np.matmul(aa.reshape((-1, 1)),aa)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [112]:
aa.reshape(1,-1)

array([[1, 2, 3]])

In [175]:
A = np.random.rand(4,4)
print(np.around(A,decimals=3))

#A = np.ones((4,4))

Q2, H2 = hessenberg_reduce2(A)
print(np.around(H2,decimals=3))


H3 = hessenberg_reduce3(A)
print(np.around(H3,decimals=3))

from scipy import linalg

HS = linalg.hessenberg(A)
print(np.around(HS,decimals=3))

[[0.948 0.315 0.927 0.24 ]
 [0.239 0.532 0.035 0.181]
 [0.206 0.251 0.177 0.076]
 [0.532 0.092 0.368 0.947]]
[[ 0.948 -0.637 -0.772  0.12 ]
 [-0.619  1.054  0.023 -0.049]
 [ 0.    -0.15   0.204  0.347]
 [ 0.     0.     0.019  0.397]]
[[ 0.948 -0.637 -0.772  0.12 ]
 [-0.619  1.054  0.023 -0.049]
 [ 0.    -0.15   0.204  0.347]
 [ 0.     0.     0.019  0.397]]
[[ 0.948 -0.637 -0.772  0.12 ]
 [-0.619  1.054  0.023 -0.049]
 [ 0.    -0.15   0.204  0.347]
 [ 0.     0.     0.019  0.397]]


In [176]:
w,_ = linalg.eig(A)
print(w)

w,_ = linalg.eig(H2)
print(w)

[1.58740944+0.j 0.04986238+0.j 0.57013275+0.j 0.3960946 +0.j]
[1.58740944+0.j 0.04986238+0.j 0.57013275+0.j 0.3960946 +0.j]


In [180]:
print(np.around(Q2 @ Q2.T, decimals=5))

[[ 1.  0.  0.  0.]
 [ 0.  1. -0. -0.]
 [ 0. -0.  1. -0.]
 [ 0. -0. -0.  1.]]


In [183]:
print(np.around(Q2 @ A @ Q2.T, decimals=3))

[[ 0.948 -0.637 -0.772  0.12 ]
 [-0.619  1.054  0.023 -0.049]
 [ 0.    -0.15   0.204  0.347]
 [ 0.    -0.     0.019  0.397]]
