In [115]:
import numpy as np
from scipy.linalg import lu

# Konkrétní matice pro výpočet

In [116]:
n = 5
A = np.array([[-float(k < l) for k in range(n)] for l in range(n)]) + np.eye(n) \
+np.array([[float(k == n-1) for k in range(n)] for l in range(n)])
A[-1,-1] = 1

In [117]:
A

array([[ 1.,  0.,  0.,  0.,  1.],
       [-1.,  1.,  0.,  0.,  1.],
       [-1., -1.,  1.,  0.,  1.],
       [-1., -1., -1.,  1.,  1.],
       [-1., -1., -1., -1.,  1.]])

In [120]:
L,U,P = lu(A)

In [123]:
P

array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  4.],
       [ 0.,  0.,  0.,  1.,  8.],
       [ 0.,  0.,  0.,  0., 16.]])

In [95]:
np.linalg.cond(A)

2.223923440475879

In [96]:
x = np.random.rand(n,1)

In [97]:
x

array([[0.80270435],
       [0.10634318],
       [0.10083739],
       [0.75704681],
       [0.60130165]])

In [98]:
b = A @ x

In [99]:
b

array([[ 1.404006  ],
       [-0.09505952],
       [-0.20690849],
       [ 0.34846354],
       [-1.16563008]])

# úkol a)

In [100]:
P, L, U = lu(A)

In [101]:
P

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
L

array([[ 1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.],
       [-1., -1.,  1.,  0.,  0.],
       [-1., -1., -1.,  1.,  0.],
       [-1., -1., -1., -1.,  1.]])

In [103]:
U

array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  4.],
       [ 0.,  0.,  0.,  1.,  8.],
       [ 0.,  0.,  0.,  0., 16.]])

array([[ 1.,  0.,  0.,  0.,  1.],
       [-1.,  1.,  0.,  0.,  1.],
       [-1., -1.,  1.,  0.,  1.],
       [-1., -1., -1.,  1.,  1.],
       [-1., -1., -1., -1.,  1.]])

# úkol b)

# úkol c)

In [107]:
Q, R = np.linalg.qr(A)

In [108]:
Q

array([[-4.47213595e-01,  2.23606798e-01,  7.62492852e-02,
         2.00841232e-16,  8.62662186e-01],
       [ 4.47213595e-01, -7.82623792e-01,  3.81246426e-02,
         8.06163052e-17,  4.31331093e-01],
       [ 4.47213595e-01,  3.35410197e-01, -8.00617494e-01,
         2.09255486e-18,  2.15665546e-01],
       [ 4.47213595e-01,  3.35410197e-01,  4.19371068e-01,
        -7.07106781e-01,  1.07832773e-01],
       [ 4.47213595e-01,  3.35410197e-01,  4.19371068e-01,
         7.07106781e-01,  1.07832773e-01]])

In [109]:
R

array([[-2.23606798e+00, -8.94427191e-01, -4.47213595e-01,
         0.00000000e+00,  1.34164079e+00],
       [ 0.00000000e+00, -1.78885438e+00, -3.35410197e-01,
         0.00000000e+00,  4.47213595e-01],
       [ 0.00000000e+00,  0.00000000e+00, -1.63935963e+00,
         0.00000000e+00,  1.52498570e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.41421356e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.72532437e+00]])

# úkol d)

In [111]:
W, S, V = np.linalg.svd(A)

In [112]:
W

array([[-2.22044605e-16, -7.77156117e-16,  1.40165657e-15,
         4.01682464e-17, -1.00000000e+00],
       [ 2.41816250e-01, -7.12015746e-01, -6.59210496e-01,
         1.54288040e-16, -2.77555756e-16],
       [ 4.52990541e-01, -5.17957311e-01,  7.25616837e-01,
        -1.79709821e-16,  1.44328993e-15],
       [ 6.06763739e-01,  3.35226641e-01, -1.39502200e-01,
        -7.07106781e-01, -4.44089210e-16],
       [ 6.06763739e-01,  3.35226641e-01, -1.39502200e-01,
         7.07106781e-01, -4.44089210e-16]])

In [113]:
S

array([3.14510269, 1.66907909, 1.5239764 , 1.41421356, 1.41421356])

In [114]:
V

array([[-6.06763739e-01, -4.52990541e-01, -2.41816250e-01,
         0.00000000e+00,  6.06763739e-01],
       [ 3.35226641e-01, -5.17957311e-01, -7.12015746e-01,
         0.00000000e+00, -3.35226641e-01],
       [ 1.39502200e-01, -7.25616837e-01,  6.59210496e-01,
         0.00000000e+00, -1.39502200e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00,  0.00000000e+00],
       [-7.07106781e-01, -3.33066907e-16,  1.41553436e-15,
         0.00000000e+00, -7.07106781e-01]])

# Hilbertova matice

In [82]:
nh = 10
Ah = np.array([[1/(i+j+1) for j in range(nh)] for i in range(nh)])

In [83]:
Ah

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [84]:
np.linalg.cond(Ah)

16024416992541.715

In [87]:
xh = np.random.rand(nh,1)

In [88]:
bh = Ah @ xh

In [90]:
bh

array([[1.14160817],
       [0.81727128],
       [0.66112335],
       [0.56175087],
       [0.49093597],
       [0.43719118],
       [0.39469657],
       [0.36010258],
       [0.33131238],
       [0.30693229]])