In [1]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(precision=4, suppress=True)
from rogues import lauchli # Python and Numpy port of Prof. Nicholas Higham's matlab test matrices

In [36]:
def bidiagonal(A):
    m, n = A.shape
    assert m == n, 'Not a square matrix.'

    U = np.eye(m)
    V = np.eye(m)
    B = A.copy()

    for k in range(n-1):
        v = np.copy(B[k:, k]) #vemu k-tý sloupec, od k+1 prvku
        v[0] = v[0] + np.sign(v[0])*la.norm(v)
        v = (v / la.norm(v)).reshape(-1,1)
        
        B[k:, k:] = B[k:, k:] - 2 * v @ (v.T @ B[k:, k:])     
        U[k:] = U[k:] - 2 * v @ (v.T @ U[k:])
        
        v = np.copy(B[k, k+1:]) #vemu k-tý sloupec, od k+1 prvku
        v[0] = v[0] + np.sign(v[0])*la.norm(v)
        v = (v / la.norm(v)).reshape(-1,1)

        B[:, k+1:] = B[:, k+1:] - 2 * (B[:, k+1:] @ v) @ v.T                                             
        V[k+1:] = V[k+1:] - 2 * v @ (v.T @ V[k+1:])
        
    return U.T, V.T, B

In [38]:
A = np.random.rand(10,10)
#A = lauchli(20, 1e-7)
#A = np.array([[1.,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

U, V, B = hessenberg(A)

#print(Q)
print(B)
    

[[-1.952   4.7185 -0.      0.     -0.     -0.      0.      0.      0.
   0.    ]
 [-0.      2.2061  1.2061  0.      0.      0.      0.      0.      0.
   0.    ]
 [-0.      0.     -0.7883 -0.7852  0.      0.     -0.     -0.      0.
   0.    ]
 [-0.      0.      0.     -0.6192 -0.8877  0.      0.     -0.     -0.
  -0.    ]
 [-0.     -0.      0.     -0.      0.7166 -0.6286  0.      0.      0.
   0.    ]
 [-0.     -0.      0.      0.      0.     -0.2878  0.3653  0.      0.
   0.    ]
 [-0.     -0.      0.      0.      0.      0.      0.4068  0.1773  0.
   0.    ]
 [-0.     -0.     -0.     -0.      0.      0.      0.     -0.5236  0.3101
  -0.    ]
 [-0.      0.     -0.     -0.      0.      0.     -0.      0.      0.2543
   0.8653]
 [ 0.      0.      0.     -0.      0.      0.      0.      0.     -0.
   0.2532]]


In [29]:
print(U.T@A@V)

[[-1.986   4.2618  0.      0.     -0.      0.      0.     -0.      0.
   0.    ]
 [ 0.      2.0222  1.035   0.     -0.     -0.     -0.     -0.      0.
   0.    ]
 [-0.      0.     -1.0279  0.6798 -0.      0.      0.      0.     -0.
  -0.    ]
 [ 0.      0.      0.     -0.8679  0.3724 -0.      0.     -0.     -0.
  -0.    ]
 [ 0.     -0.      0.      0.     -0.7422 -0.5134  0.     -0.     -0.
  -0.    ]
 [ 0.     -0.      0.      0.     -0.      0.6668 -0.7858  0.      0.
  -0.    ]
 [ 0.      0.      0.      0.     -0.     -0.     -0.4005  0.5651 -0.
   0.    ]
 [-0.      0.     -0.     -0.     -0.      0.      0.      0.4881  0.2258
  -0.    ]
 [-0.     -0.      0.     -0.      0.      0.     -0.     -0.     -0.308
   0.1451]
 [ 0.     -0.      0.     -0.      0.     -0.      0.     -0.     -0.
  -0.3014]]


In [39]:
np.allclose(U.T@A@V, B)

True

In [60]:
def hessenberg(A):
    m, n = A.shape
    H = A.copy() # Transformed matrix so far
    Q = np.eye(n) # Orthogonal transform so far
    

    for j in range(n-2):
        v = H[j+1:, j] #vemu j-tý sloupec, od j+1 prvku
        
        norm_v = np.linalg.norm(v) # vypočtu z něj normu
        v[0] = v[0] + np.sign(v[0])*norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,1)
        
        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * v @ (v.T @ H[j+1:, j+1:])
        H[j+1, j] = norm_v
        H[j+2:, j] = 0
        H[:, j+1:] = H[:, j+1:] - 2 * (H[:, j+1:] @ v) @ v.T
                                             
        Q[j+1:] = Q[j+1:] - 2 * v @ (v.T @ Q[j+1:])
        
    return Q, H

In [124]:
def hessenberg(A):
    _, n = A.shape
    H = np.eye(n)
    q = np.eye(n)
    h = A.copy()
    
    for i in range(n-2):
        x = h[i+1:, i].reshape(-1,1)
        u = x.reshape(-1,1)
        print(u)
        u[0] = x[0] + np.sign(x[0])*np.linalg.norm(x)
        hi = np.eye(len(u)) - (2*u@u.T)/(u.T@u)
        Hi = H.copy()
        Hi[i+1:,i+1:] = hi
        print(hi)
        h = Hi @ h @ Hi.T
        q = Hi @ q
    return q, h
        

In [155]:
Q@A@Q.T

array([[ 0.2003, -0.7246, -0.6773,  0.0315,  0.1586],
       [-0.9893,  1.4046,  1.241 ,  0.3223,  0.2906],
       [ 0.    ,  1.0102,  1.0044, -0.0651,  0.6804],
       [-0.    ,  0.    ,  0.4258, -0.5512, -0.08  ],
       [-0.    ,  0.    ,  0.    , -0.5395, -0.2388]])

In [156]:
H

array([[ 0.2003, -0.7246, -0.6773,  0.0315,  0.1586],
       [-0.9893,  1.4046,  1.241 ,  0.3223,  0.2906],
       [ 0.    ,  1.0102,  1.0044, -0.0651,  0.6804],
       [ 0.    ,  0.    ,  0.4258, -0.5512, -0.08  ],
       [ 0.    ,  0.    ,  0.    , -0.5395, -0.2388]])

In [105]:
Q@Q.T

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0., -0.],
       [ 0., -0.,  0.,  1., -0.],
       [ 0.,  0., -0., -0.,  1.]])

In [84]:
A = np.random.rand(5,5)

In [85]:
A

array([[0.6961, 0.6668, 0.5094, 0.0731, 0.8115],
       [0.3627, 0.144 , 0.0354, 0.1618, 0.3231],
       [0.0531, 0.3915, 0.0983, 0.6933, 0.391 ],
       [0.9674, 0.6627, 0.2019, 0.7462, 0.1849],
       [0.7137, 0.7391, 0.1475, 0.128 , 0.1285]])

In [86]:
H = A.copy()
Q = np.eye(A.shape[0])
Q

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
x = H[1:,0]
print(x)
q = x + np.sign(x[0])*np.linalg.norm(x)*np.array([1,0,0,0])
q = q/np.linalg.norm(q)
q = q.reshape(-1,1)
print(q)
Hi = np.eye(4) - 2*q@q.T
print(Hi)
Hf = 

[0.3627 0.0531 0.9674 0.7137]
[[0.8027]
 [0.0263]
 [0.4795]
 [0.3537]]
[[-0.2886 -0.0422 -0.7697 -0.5679]
 [-0.0422  0.9986 -0.0252 -0.0186]
 [-0.7697 -0.0252  0.5402 -0.3392]
 [-0.5679 -0.0186 -0.3392  0.7498]]
[-1.2568  0.      0.     -0.    ]


In [37]:
def bidig(A):
    m, n = A.shape
    U = np.eye(m) 
    V = np.eye(n) 
    
    for k in range(n):
        x = np.copy(A[k:, k])
        v = A[k:, k] 
        v[0] = 1.
        
        norm_v = np.linalg.norm(x) # vypočtu z něj normu
        print(f'norm: {norm_v}')
        v[0] = x[0] + np.sign(x[0])*norm_v
        
        
        #v[0] = -np.inner(x[1:],x[1:])/(x[0]+norm_v)
        
        v = v / np.linalg.norm(v)
        #v = v.reshape(-1,1)
        
        print(f'v:{v}')

In [38]:
A = np.arange(1,13.0).reshape(4,3)
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [39]:
bidig(A)

norm: 12.884098726725126
v:[0.734  0.2115 0.3701 0.5287]
norm: 13.638181696985855
v:[0.7326 0.4004 0.5505]
norm: 12.041594578792296
v:[0.7359 0.6771]


In [1]:
  

    for j in range(n-2):
        v = H[j+1:, j] #vemu j-tý sloupec, od j+1 prvku
        
        norm_v = np.linalg.norm(v) # vypočtu z něj normu
        v[0] = v[0] + np.sign(v[0])*norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,1)
        
        H[j+1:, j+1:] = H[j+1:, j+1:] - 2 * v @ (v.T @ H[j+1:, j+1:])
        H[j+1, j] = norm_v
        H[j+2:, j] = 0
        H[:, j+1:] = H[:, j+1:] - 2 * (H[:, j+1:] @ v) @ v.T
                                             
        Q[j+1:] = Q[j+1:] - 2 * v @ (v.T @ Q[j+1:])
        
    return Q, H

In [258]:
def hessenberg(A):
    m, n = A.shape
    Q = np.eye(m)
    H = A.copy()
    S = np.eye(m)

    for k in range(n-2):
        v = np.copy(H[k+1:, k]) # k-tý sloupec, od k+1 prvku
        print(v)
        norm_v = np.sign(v[0])*np.linalg.norm(v)
        v[0] = v[0] + norm_v
        v = v / np.linalg.norm(v)
        v = v.reshape(-1,1)
        print(f'v_norm: {la.norm(v)}')
        print(f'v: {v}')
       
        #H[k+1:, k:] = H[k+1:, k:] - 2 * (v @ (v.T @ H[k+1:, k:])) # nasobeni zleva
        #H[k+1:, k:] = H[k+1:, k:] - 2 * (np.matmul(v,(np.matmul(v.T,H[k+1:, k:])))) # nasobeni zleva
        #print(f'H:\n{H}')
        #H[k+1, k] = -norm_v
        #H[k+2:, k] = 0
        #H[:, k+1:] = H[:, k+1:] - 2 * (H[:, k+1:] @ v) @ v.T # násobení zprava
                                             
        Q[k+1:] = Q[k+1:] - 2 * v @ (v.T @ Q[k+1:])
        S = np.eye(m)
        S[k+1:,k+1:] = S[k+1:,k+1:] - 2* v @ v.T / (v.T @ v)
        
        #print(f'Q{k}:\n{Q}')
        #print(f'Q@Q.T:\n{Q@Q.T}')
        #print(f'S:\n{S}')
        #print(f'S@H:\n{S@H}')
        H = np.copy(S @ H) 
        #H[k+1, k] = -norm_v
        #H[k+2:, k] = 0
        H = np.copy(H @ S.T)
        #print(f'H{k}:\n {H}')        
        
    return Q, H

In [259]:
A = np.arange(1,17.0).reshape(4,4)
#A = np.random.rand(5,5)
A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [260]:
Q,H = hessenberg(A)

[ 5.  9. 13.]
v_norm: 1.0
v: [[0.8067]
 [0.3364]
 [0.4859]]
[0.3586 2.1797]
v_norm: 1.0
v: [[0.7623]
 [0.6472]]


In [261]:
Q

array([[ 1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    , -0.3015, -0.5427, -0.7839],
       [ 0.    ,  0.8616,  0.1969, -0.4677],
       [ 0.    ,  0.4082, -0.8165,  0.4082]])

In [262]:
H

array([[  1.    ,  -5.3669,   0.4431,   0.    ],
       [-16.5831,  33.0873,  -9.5575,  -0.    ],
       [ -0.    ,  -2.209 ,  -0.0873,  -0.    ],
       [ -0.    ,  -0.    ,  -0.    ,  -0.    ]])

In [263]:
Q@A@Q.T

array([[  1.    ,  -5.3669,   0.4431,   0.    ],
       [-16.5831,  33.0873,  -9.5575,  -0.    ],
       [ -0.    ,  -2.209 ,  -0.0873,  -0.    ],
       [ -0.    ,  -0.    ,  -0.    ,  -0.    ]])

In [241]:
Q@Q.T

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.,  0.],
       [ 0., -0.,  1.,  0., -0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  1.]])